package com.zengshi.ecp.wxbase.util;

import java.io.Serializable;

/**
 * 
 * Title: 查询条件父类 <br>
 * project:lacemall-web <br>
 * Date:2016年4月6日<br>
 * 
 * @author linwb
 */
@SuppressWarnings("serial")
public abstract class BaseExample implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table bizres_company
	 *
	 * @mbggenerated
	 */
	protected Integer limitStart;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table bizres_company
	 *
	 * @mbggenerated
	 */
	protected Integer limitEnd;

	public Integer getLimitStart() {
		return limitStart;
	}

	public void setLimitStart(Integer limitStart) {
		this.limitStart = limitStart;
	}

	public Integer getLimitEnd() {
		return limitEnd;
	}

	public void setLimitEnd(Integer limitEnd) {
		this.limitEnd = limitEnd;
	}

}
